online_shop/cart/urls.py
import cart.views

import django.urls


app_name = 'cart'

urlpatterns = [
    django.urls.path('', cart.views.CartDetailView.as_view(), name='detail'),
    django.urls.path(
        'add/<int:product_pk>/',
        cart.views.AddProductToCartView.as_view(),
        name='add_product',
    ),
    django.urls.path(
        'remove/<int:product_pk>/',
        cart.views.RemoveProductFromCartView.as_view(),
        name='remove_product',
    ),
]

online_shop/coupons/urls.py
import coupons.views

import django.urls


app_name = 'coupons'

urlpatterns = [
    django.urls.path(
        'activate/',
        coupons.views.CouponActivateView.as_view(),
        name='activate',
    )
]

online_shop/online_shop/urls.py
import django.conf
import django.conf.urls.static
import django.contrib
import django.contrib.admin.sites
import django.contrib.staticfiles.urls
import django.urls


urlpatterns = [
    django.urls.path('', django.urls.include('shop.urls')),
    django.urls.path('cart/', django.urls.include('cart.urls')),
    django.urls.path('orders/', django.urls.include('orders.urls')),
    django.urls.path('payment/', django.urls.include('payment.urls')),
    django.urls.path('coupons/', django.urls.include('coupons.urls')),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path(
        'ckeditor/', django.urls.include('ckeditor_uploader.urls')
    ),
    django.urls.path('rosetta/', django.urls.include('rosetta.urls')),
]

if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include('debug_toolbar.urls')
        ),
    )
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    else:
        urlpatterns += (
            django.contrib.staticfiles.urls.staticfiles_urlpatterns()
        )

online_shop/orders/urls.py
import orders.views

import django.urls


app_name = 'orders'

urlpatterns = [
    django.urls.path(
        'create/', orders.views.OrderCreateView.as_view(), name='create'
    ),
    django.urls.path(
        '<int:order_pk>/pdf/',
        orders.views.GetOrderInPdfView.as_view(),
        name='order_pdf',
    ),
]

online_shop/shop/urls.py
import shop.views

import django.urls


app_name = 'shop'

urlpatterns = [
    django.urls.path(
        '', shop.views.ProductListView.as_view(), name='products'
    ),
    django.urls.path(
        'categories/<int:category_pk>/',
        shop.views.ProductListView.as_view(),
        name='products_by_category',
    ),
    django.urls.path(
        '<int:product_pk>/',
        shop.views.ProductDetailView.as_view(),
        name='product',
    ),
]

online_shop/cart/forms.py
import django.forms
from django.utils.translation import gettext_lazy as _


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class AddProductToCartForm(django.forms.Form):
    """форма добавления товара в корзину"""

    quantity = django.forms.TypedChoiceField(
        label=_('Quantity'),
        help_text=_('Choose quantity of products'),
        coerce=int,
        choices=PRODUCT_QUANTITY_CHOICES,
    )
    override_quantity = django.forms.BooleanField(
        required=False, initial=False, widget=django.forms.HiddenInput
    )

online_shop/cart/views.py
import cart.cart
import cart.forms
import coupons.forms
import shop.models
import shop.recommender
import shop.services

import django.http
import django.shortcuts
import django.views.generic


class AddProductToCartView(django.views.generic.View):
    """добавляем товар в корзину"""

    def post(
        self, request: django.http.HttpRequest, product_pk: int
    ) -> django.http.HttpResponse:
        cart_obj = cart.cart.Cart(request)
        product = shop.services.get_product_or_404(pk=product_pk)
        form = cart.forms.AddProductToCartForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            cart_obj.add_product(
                product=product,
                quantity=data['quantity'],
                override_quantity=data['override_quantity'],
            )
        return django.shortcuts.redirect('cart:detail')


class RemoveProductFromCartView(django.views.generic.View):
    """удалить товар из корзины"""

    def post(
        self, request: django.http.HttpRequest, product_pk: int
    ) -> django.http.HttpResponse:
        cart_obj = cart.cart.Cart(request)
        product = shop.services.get_product_or_404(pk=product_pk)
        cart_obj.remove_product(product=product)
        return django.shortcuts.redirect('cart:detail')


class CartDetailView(django.views.generic.View):
    """просмотр корзины товаров"""

    def get(
        self, request: django.http.HttpRequest
    ) -> django.http.HttpResponse:
        """просмотр корзины товаров"""
        cart_obj = cart.cart.Cart(request)
        items = [item for item in cart_obj]
        for item in items:
            item['update_quantity'] = cart.forms.AddProductToCartForm(
                initial={
                    'quantity': item['quantity'],
                    'override_quantity': True,
                }
            )
        total_price = cart_obj.get_total_price()
        total_price_after_discount = cart_obj.get_total_price_after_discount()
        discount = total_price - total_price_after_discount
        return django.shortcuts.render(
            request,
            'cart/detail.html',
            {
                'cart': cart_obj,
                'cart_items': items,
                'coupon_activate_form': coupons.forms.CouponActivateForm(),
                'recommended_products': (
                    shop.recommender.Recommender().suggest_products_for(
                        [item['product'] for item in items], max_results=4
                    )
                ),
                'total_price': total_price,
                'total_price_after_discount': total_price_after_discount,
                'discount': discount,
            },
        )

online_shop/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
  {% trans "Cart" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Cart" %}</h1>
  <table class="cart">
    <thead>
      <tr>
      <th>{% trans "Image" %}</th>
      <th>{% trans "Product" %}</th>
      <th>{% trans "Quantity" %}</th>
      <th>{% trans "Delete" %}</th>
      <th>{% trans "Unit price" %}</th>
      <th>{% trans "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart_items %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.get_image_300x300.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:add_product" product.pk %}" method="post">
                {% csrf_token %}
                {{ item.update_quantity.quantity }}
                {{ item.update_quantity.override_quantity }}
                <input type="submit" value="{% trans "Update" %}">
              </form>
            </td>
            <td>
              <form action="{% url "cart:remove_product" product.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="{% trans "Delete" %}">
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% with coupon=cart.get_coupon %}
        {% if coupon %}
          <tr class="subtotal">
            <td>{% trans "Subtotal" %}</td>
            <td colspan="4"></td>
            <td class="num">${{ total_price|floatformat:2 }}</td>
          </tr>
          <tr>
            <td>
              "{{ coupon.code }}" {% trans "coupon" %}
              ({{ coupon.discount }}% {% trans "discount" %})
            </td>
            <td colspan="4"></td>
            <td class="num neg">
            – ${{ discount|floatformat:2 }}
            </td>
          </tr>
        {% endif %}
      {% endwith %}
      <tr class="total">
        <td>{% trans "Total" %}</td>
        <td colspan="4"></td>
        <td class="num">${{ total_price_after_discount|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>
  {% if recommended_products %}
    <div class="recommendations">
    <h3>{% trans "People who bought this also bought" %}:</h3>
    {% for product in recommended_products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.get_image_300x300.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <p><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
      </div>
    {% endfor %}
    </div>
  {% endif %}
  <p>{% trans "Activate coupon" %}:</p>
  <form action="{% url "coupons:activate" %}" method="post">
    {% csrf_token %}
    {{ coupon_activate_form.code.label }}:
    {{ coupon_activate_form.code }}
    <input type="submit" value="{% trans "Activate" %}">
  </form>
  <p class="text-right">
    <a href="{% url "shop:products" %}" class="button light">{% trans "Products" %}</a>
    <a href="{% url "orders:create" %}" class="button">
      {% trans "Make an order" %}
    </a>
  </p>
{% endblock %}