online_shop/cart/urls.py
import cart.views

import django.urls


app_name = 'cart'

urlpatterns = [
    django.urls.path('', cart.views.CartDetailView.as_view(), name='detail'),
    django.urls.path(
        'add/<int:product_pk>/',
        cart.views.AddProductToCartView.as_view(),
        name='add_product',
    ),
    django.urls.path(
        'remove/<int:product_pk>/',
        cart.views.RemoveProductFromCartView.as_view(),
        name='remove_product',
    ),
]

online_shop/online_shop/urls.py
import django.conf
import django.conf.urls.static
import django.contrib
import django.contrib.admin.sites
import django.contrib.staticfiles.urls
import django.urls


urlpatterns = [
    django.urls.path('', django.urls.include('shop.urls')),
    django.urls.path('cart/', django.urls.include('cart.urls')),
    django.urls.path('orders/', django.urls.include('orders.urls')),
    django.urls.path('payment/', django.urls.include('payment.urls')),
    django.urls.path('coupons/', django.urls.include('coupons.urls')),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path(
        'ckeditor/', django.urls.include('ckeditor_uploader.urls')
    ),
    django.urls.path('rosetta/', django.urls.include('rosetta.urls')),
]

if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include('debug_toolbar.urls')
        ),
    )
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    else:
        urlpatterns += (
            django.contrib.staticfiles.urls.staticfiles_urlpatterns()
        )

online_shop/payment/urls.py
import payment.views
import payment.webhooks

import django.urls


app_name = 'payment'

urlpatterns = [
    django.urls.path(
        'process/', payment.views.PaymentProcessView.as_view(), name='process'
    ),
    django.urls.path(
        'complete/',
        payment.views.PaymentCompleteView.as_view(),
        name='complete',
    ),
    django.urls.path(
        'cancel/', payment.views.PaymentCancelView.as_view(), name='cancel'
    ),
    django.urls.path(
        'order-paid-webhook/',
        payment.webhooks.StripePaymentCompleteWebhookView.as_view(),
        name='order_paid_webhook',
    ),
]

online_shop/payment/views.py
import orders.models
import orders.services
import payment.stripe_services

import django.conf
import django.db.models
import django.http
import django.shortcuts
import django.urls
import django.views.generic


class PaymentProcessView(django.views.generic.TemplateView):
    """страница оформления платежа"""

    template_name = 'payment/process.html'

    def get_context_data(self, *args, **kwargs) -> dict:
        """добавляем номер заказа и сам заказ в шаблон"""
        context = super().get_context_data(*args, **kwargs)
        context['order'] = orders.services.get_order_with_coupon_and_products(
            pk=self.request.session.get('order_id')
        )
        return context

    def post(
        self, request: django.http.HttpRequest
    ) -> django.http.HttpResponse:
        """обрабатываем платеж"""
        order = orders.services.get_order_with_coupon_and_products_or_404(
            pk=request.session.get('order_id')
        )
        session = payment.stripe_services.create_payment_session_by_order(
            request, order
        )
        return django.shortcuts.redirect(session.url)


class PaymentCompleteView(django.views.generic.TemplateView):
    """оплата успешна"""

    template_name = 'payment/complete.html'


class PaymentCancelView(django.views.generic.TemplateView):
    """оплата отменена"""

    template_name = 'payment/cancel.html'

online_shop/templates/payment/cancel.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Payment cancelled" %}{% endblock %}

{% block content %}
  <h1>{% trans "Payment not processed" %}</h1>
  <p>{% trans "During payment processing an error occured" %}</p>
{% endblock %}

online_shop/templates/payment/complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Succesfull payment" %}{% endblock %}

{% block content %}
  <h1>{% trans "Succesfull payment" %}</h1>
  <p>{% trans "Payment processed succesfully" %}.</p>
{% endblock %}

online_shop/templates/payment/process.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Order payment" %}{% endblock %}

{% block content %}
  <h1>{% trans "Order" %}</h1>
  <table class="cart">
  <thead>
  <tr>
    <th>{% trans "Image" %}</th>
    <th>{% trans "Product" %}</th>
    <th>{% trans "Unit price" %}</th>
    <th>{% trans "Quantity" %}</th>
    <th>{% trans "Price" %}</th>
  </tr>
  </thead>
    <tbody>
      {% for item in order.order_products.all %}
        <tr class="row{% cycle "1" "2" %}">
          <td>
            <img src="{% if item.product.image %}{{ item.product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
          </td>
          <td>{{ item.product.name }}</td>
          <td class="num">${{ item.price }}</td>
          <td class="num">{{ item.quantity }}</td>
          <td class="num">${{ item.get_cost }}</td>
        </tr>
      {% endfor %}
      {% if order.coupon %}
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="3"></td>
          <td class="num">
            ${{ order.get_total_cost_before_discount|floatformat:2 }}
          </td>
        </tr>
        <tr>
          <td>
          "{{ order.coupon.code }}" {% trans "coupon" %}
          ({{ order.discount }}% {% trans "discount" %})
          </td>
          <td colspan="3"></td>
          <td class="num neg">
          – ${{ order.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% trans "Total" %}</td>
        <td colspan="3"></td>
        <td class="num">
        ${{ order.get_total_cost|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>
  <form action="{% url "payment:process" %}" method="post">
    <input type="submit" value="{% trans "Pay" %}">
    {% csrf_token %}
  </form>
{% endblock %}