online_shop/cart/urls.py
import cart.views

import django.urls


app_name = 'cart'

urlpatterns = [
    django.urls.path('', cart.views.CartDetailView.as_view(), name='detail'),
    django.urls.path(
        'add/<int:product_pk>/',
        cart.views.AddProductToCartView.as_view(),
        name='add_product',
    ),
    django.urls.path(
        'remove/<int:product_pk>/',
        cart.views.RemoveProductFromCartView.as_view(),
        name='remove_product',
    ),
]

online_shop/online_shop/urls.py
import django.conf
import django.conf.urls.static
import django.contrib
import django.contrib.admin.sites
import django.contrib.staticfiles.urls
import django.urls


urlpatterns = [
    django.urls.path('', django.urls.include('shop.urls')),
    django.urls.path('cart/', django.urls.include('cart.urls')),
    django.urls.path('orders/', django.urls.include('orders.urls')),
    django.urls.path('payment/', django.urls.include('payment.urls')),
    django.urls.path('coupons/', django.urls.include('coupons.urls')),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path(
        'ckeditor/', django.urls.include('ckeditor_uploader.urls')
    ),
    django.urls.path('rosetta/', django.urls.include('rosetta.urls')),
]

if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include('debug_toolbar.urls')
        ),
    )
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    else:
        urlpatterns += (
            django.contrib.staticfiles.urls.staticfiles_urlpatterns()
        )

online_shop/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}Online Shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">Online Shop</a>
    </div>
    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            {% trans "Your cart" %}:
            <a href="{% url "cart:detail" %}">
              {{ total_items }} {% trans "product" %}, 
              ${{ cart.get_total_price }}
            </a>
          {% else %}
            {% trans "Your cart is empty" %}
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>